### ISSUE TITLE
书中的源代码 建议公布一下

### ISSUE THREAD

**Issue by des726** [go-programming-tour-book/book#8]
书中的源代码 建议公布一下 ！ 
手敲打代码 太伤眼睛了！ ：）
申请将书中实例源代码公布一下！

**Comment by uquinnhau** [comment]
同感
！

**Comment by eddycjy** [comment]
@des726 @uquinnhau 都在这里面，传送门：https://github.com/go-programming-tour-book 。

又或是。。。。你们莫非指的每一小节的代码都一个个例出来吗 😳

**Comment by zhaobzh** [comment]
自己照着写一遍印象更加深刻啊

**Comment by eddycjy** [comment]
无回复，Closing。
